export const ADD_PERSON = 'ADD_PERSON'

export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS'
export const LOAD_CHANNELS_FAILURE = 'LOAD_CHANNELS_FAILURE'

export const LOAD_STREAMS_SUCCESS = 'LOAD_STREAMS_SUCCESS'
export const LOAD_STREAMS_FAILURE = 'LOAD_STREAMS_FAILURE'

